[package]
name = "evm_lab"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
hex = "0.4.3"
log = "0.4.22"
log4rs = "1.3.0"
num-bigint = "0.4.6"
num-integer = "0.1.46"
num-traits = "0.2.19"
once_cell = "1.20.2"
tiny-keccak = {version="2.0.2",features=["keccak"]}
